version: 2

sources:
  - name: raw
    database: postgres
    schema: raw
    tables:
      - name: competitions
      - name: teams
      - name: matches
      - name: standings

  - name: bronze
    tables:
      - name: fbref_schedule
      - name: fbref_player_season_stats_standard
